name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Type/Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the bug
    validations:
      required: true
  - type: textarea
    id: reproducing-steps
    attributes:
      label: Steps to Reproduce
      description: The steps to be followed to reproduce the issue.
    validations:
      required: false
  - type: textarea
    id: env-details
    attributes:
      label: OS, DB, other environment details and versions
    validations:
      required: false
