services:
  db:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: highlights
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./scripts/seed-data.sql:/docker-entrypoint-initdb.d/seed-data.sql
